# Generated by Django 4.2.1 on 2023-05-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='direction',
            field=models.CharField(choices=[('income', 'Income'), ('expend', 'Expend')], default='expend', max_length=6, verbose_name='类型'),
            preserve_default=False,
        ),
    ]
