# Generated by Django 4.2.1 on 2023-06-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_category_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.IntegerField(help_text='单位: 分', verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.category', verbose_name='类目'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_time',
            field=models.DateField(verbose_name='账单时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='direction',
            field=models.CharField(choices=[('income', '收入'), ('expend', '支出')], max_length=6, verbose_name='类型'),
        ),
    ]
